### ISSUE TITLE
Cloudfront List of Fields have Awkward Change Output

### ISSUE THREAD

**Issue by ErikBZ** [perfectsense/gyro-aws-provider#437]
Some fields for Cloudfront have awkward change output like the following:
```
cnames:  ⟳ 'cdn.scpr.example.com' → 'scpr.example1.com', + 'cdn.scpr.example.com'
```
and
```
· custom-error-response:  ⟳ custom-error-response 504 → custom-error-response 400, ⟳ custom-error-response 400 → custom-error-response 500,custom-error-response 404,custom-error-response 503,custom-error-response 403,custom-error-response 502, ⟳ custom-error-response 500 → custom-error-response 504
```

In the first example we're adding a domain to the cnames list `scpr.example1.com` but the output shows that we're updating an existing cname and adding that same existing cname again.

In the second example `customer-error-response 400` is updated but the changes show that everything is updating in some way.

**Comment by beetlebugorg** [comment]
@deepanjan90 I'd recommend making these two fields List instead of Set. I did a quick test and it provides a better output.
