### ISSUE TITLE
SQS Queue: Doesn't Support KMS Master Key Id

### ISSUE THREAD

**Issue by ssnyder-sme** [perfectsense/gyro-aws-provider#543]
I attempted to set the KMS Master Key Id for an SQS queue so that it would store data encrypted at rest, but the gyro runtime complained about it being an invalid data type. 

I specified "$(aws::kms-key logical-resource-name-in-gyro).id" as the value of this attribute and saw this error message attempting to "gyro up":

> Error: Can't set kms-master-key-id to `<REDACTED-KMS-UUID>` because it can't be converted to an instance of java.lang.Integer!

I assumed the id it refers to is the "id" output of the KMS key defined in the Gyro docs. I tried with the "arn" output as well, but same error message. 

Gyro: https://gyro.dev/providers/aws/sqs/sqs-queue.html
Gyro: https://gyro.dev/providers/aws/kms/kms-key.html

I'm running version 1.1.0 of Gyro on a Mac.

**Comment by ssnyder-sme** [comment]
Thank you very much!

**Comment by ssnyder-sme** [comment]
I don't see it in the README, but how to fixes like this get into the deployed Gyro?

**Comment by deepanjan90** [comment]
Just made a comment https://github.com/perfectsense/sony-ops/pull/10#issuecomment-1020354999

We made a patch, so you will just need to update the `gyro-aws-provider` provider version to get it woring.
