### ISSUE TITLE
Unable to configure Kinesis Firehose ARN for WAF v2 logging configuration

### ISSUE THREAD

**Issue by ssnyder-sme** [perfectsense/gyro-aws-provider#559]
According to the WAF v2 docs (https://gyro.dev/providers/aws/waf-v2/wafv2-web-acl.html) we should be able to set the WAF logging configuration in the gyro definition, but I'm unable to successfully set the ARN for a Kinesis Firehose. 

It looks to be defined as a set, but I've tried to specify the Kinesis Firehose ARN as a list and as a single string.

Also is the error message a typo? Should be "At least one of" instead of "Atleast one off"

Example config:
![Screen Shot 2022-02-23 at 5 14 59 PM](https://user-images.githubusercontent.com/69162122/155438366-2d1d3fc8-cfa0-4804-8b49-c728d3a99e82.png)

Errors when running gyro up
> aws::wafv2-web-acl web-acl → logging-configuration : Atleast one off 'redacted-field' or 'log-destination-configs' needs to be set.

**Comment by ssnyder-sme** [comment]
Looks like a code fix was merged in. Will there be a release created to include the fix?

**Comment by beetlebugorg** [comment]
We're testing now and we'll do a release shortly.

**Comment by ssnyder-sme** [comment]
Thanks!

**Comment by deepanjan90** [comment]
`gyro-aws-provider` release `1.4.7` is now ready

Release notes can be found here : https://github.com/perfectsense/gyro-aws-provider/releases/tag/release%2F1.4.7

**Comment by ssnyder-sme** [comment]
It's working in v1.4.7. Thank you!
